<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MinimalBastion</AssemblyName>
    <RootNamespace>MinimalBastion</RootNamespace>
    <ApplicationIcon />
    <StartupObject>MinimalBastion.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU</Platforms>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5" />
  </ItemGroup>

  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
    <None Update="ContentData\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
